services:
  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    volumes:
      - frontend-dist:/app/dist

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - frontend-build

volumes:
  frontend-dist:
